services:
  - type: web
    name: atd-task-manager
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: atd-database
          property: connectionString

databases:
  - name: atd-database
    plan: free
    databaseName: atd
    user: atd_user
